stages:
  - analyse
  - build
  - deploy
  - archive

analyse:
  stage: analyse
  image: cirrusci/flutter:stable
  before_script:
    - echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" > .env
    - flutter pub get
  script:
    - flutter analyze
  only:
    - main
    - develop

android:release:
  stage: archive
  image: cirrusci/flutter:stable
  before_script:
    - flutter pub get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --release
  artifacts:
    paths:
      - "**/**/**/**/**/**/*.apk"
  only:
    - main
    - develop

web:build:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" > .env
    - flutter pub get
  script:
    - flutter build web
    - flutter analyze
  artifacts:
    paths:
      - build/web
  only:
    - main
    - develop

web:deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || apt-get install rsync -y'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - cp -r build/web public
    - rsync -avuz -e 'ssh -o StrictHostKeyChecking=no' public/ ${DEPLOY_PATH}/${CI_COMMIT_BRANCH}
  artifacts:
    paths:
      - public
  only:
    - main
    - develop