build_web:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" > .env
    - flutter pub get
  script:
    - flutter build web
    - flutter analyze
  artifacts:
    paths:
      - build/web
 
deploy:
  stage: deploy
  before_script:
    - apt-get update
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - 'which rsync || ( apt-get install -qq rsync )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    - cp -r build/web public
    - rsync -avuz -e 'ssh -o StrictHostKeyChecking=no' public/ ${DEPLOY_PATH}/${CI_COMMIT_BRANCH}
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
